# Site Settings
title: "Barun Barik"
description: "Personal Blog & Profile"
url: "https://barunbarik.com" # Your custom domain
baseurl: "" # Leave empty

# Theme Settings
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "default" # Options: air, aqua, contrast, dark, dirt, sunrise

include: ["_pages"]

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

author:
  name: "Barun Barik"
  bio: "Writer, Developer, and Creator."
  location: "Tampa"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/barunbarik"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/barunbarik"
